name: Test Push

on: 
  push:

jobs:
  TestPush:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: For test learn
        run: echo "pushed successfully"

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Run the python file
        run: python "hello.py"
